### PR TITLE
fix issue 13

### LINKED ISSUE #13: Marshalling fails with Interface members when they are nil
I was migrating some marshalling code to use this library over the standard library (thank you for making it!) and encountered this error. Note that the stdlib reports a nil error with data, while `segmentio/encoding/json` returns an error. i

Minimal repro:
```go
package main

import (
	"fmt"

	"github.com/segmentio/encoding/json"
)

type segmentJSON struct {
	Stringer fmt.Stringer
	Field    int `json:"MyInt"`
}

func main() {
	fmt.Println("segment-error")
	js := segmentJSON{Field: 2}
	fmt.Println(json.Marshal(js))
}
```

Output when using `encoding/json`:
```bash
❯ go run main.go
segment-error
[123 34 83 116 114 105 110 103 101 114 34 58 110 117 108 108 44 34 77 121 73 110 116 34 58 50 125] <nil>
```

with `github.com/segmentio/encoding/json`:
```
❯ go run main.go
segment-error
[] json: unsupported type: fmt.Stringer
```

### PR DESCRIPTION
**Pull request by achille-roussel**
Fixes #13 

The `encoding/json` package does a bit of special magic when it comes to decoding into non-empty interface types:
- if the underlying value is nil it always accepts the `null` value but refuses everything else
- if the underlying value is a non-nill pointer type it will attempt to decode JSON into the value

### CODE REVIEW

File: json/codec.go [hunk 1]
```diff
@@ -169,9 +172,6 @@ func constructCodec(t reflect.Type, seen map[reflect.Type]*structType) (c codec)
 
 	case reflect.Ptr:
 		c = constructPointerCodec(t, seen)
-
-	default:
-		c = constructUnmarshalTypeErrorCodec(t)
```
Comment (pelletier) [inline json/codec.go]: Don't we want to keep the catch-all error case?

Comment (achille-roussel) [reply json/codec.go]: I replaced it below with checks for `c.encode == nil` and `c.decode == nil`, but yes this one is probably more clear, I'll revert 👍

**Comment by achille-roussel** [comment]
Thanks for the review!
