### PR TITLE
fix issue 18

### LINKED ISSUE #18: Decoder hangs when decoding invalid json
```go
func TestHangingDecoder(t *testing.T) {
	b := []byte(`{
	"userId": "blah",
	}`)

	d := NewDecoder(bytes.NewReader(b))

	var a struct {
		UserId string `json:"userId"`
	}
	err := d.Decode(&a)
	if err == nil {
		t.Fatal("should have errored")
	}
}
```

This test hangs on master. Light on details for now, will add more when I have them.

Looks like it's an issue in Decoder. It works fine with `Unmarshal`:

```go
// this works
func TestHangingDecoder(t *testing.T) {
	b := []byte(`{
	"userId": "blah",
	}`)
	var a struct {
		UserId string `json:"userId"`
	}
	err := Unmarshal(b, &a)
	if err == nil {
		t.Fatal("should have errored")
	}
}
```

### PR DESCRIPTION
**Pull request by achille-roussel**
Fixes #18 

Fixes the issue where we had an infinite loop in the decode when parsing some invalid JSON.

### CODE REVIEW

File: json/parse.go [hunk 1]
```diff
@@ -558,6 +575,12 @@ func parseObject(b []byte) ([]byte, []byte, error) {
 				return nil, b, syntaxError(b, "expected ',' after object field value but found '%c'", b[0])
 			}
 			b = skipSpaces(b[1:])
+			if len(b) == 0 {
+				return nil, b, unexpectedEOF(b)
+			}
+			if b[0] == '}' {
+				return nil, b, syntaxError(b, "unexpected trailing comma after object field")
+			}
```
Comment (achille-roussel) [inline json/parse.go]: I added these checks to make error messages more representative of error cases.

File: json/json.go [hunk 2]
```diff
@@ -287,6 +277,19 @@ func (dec *Decoder) readValue() (v []byte, err error) {
 				dec.remain = skipSpaces(r)
```
Comment (rarchana2001asu) [inline json/json.go]: Not relevant to this PR but do we need to update dec.err here similar to https://github.com/segmentio/encoding/pull/19/files#diff-0839e8ccea528964240d6791f5a24cafR312?

Comment (achille-roussel) [reply json/json.go]: No, `dec.err` is supposed to retain the last non-nil error, if we update it here it'll erase the last error seen by the decoder (since we just successfully parsed a JSON value).

**Comment by achille-roussel** [comment]
Thanks for the reviews!
